title: Script ubuntu
description: Crear un Script  como ejecutarlo en terminal y de forma gráfica con Read Key para que no se cierre la terminal hasta presionar la tecla espacio , ejemplo sencillo con actualizar
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
